version: "3.8"

services:
  backend:
    image: shoebak/attendance-backend:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_net

  frontend:
    image: shoebak/attendance-frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_net
    depends_on:
      - backend

networks:
  app_net:
    driver: overlay

